###服务启动端口号
server:
  port: 8083
spring:
  ###数据库相关连接
  datasource:
    url: jdbc:mysql://localhost:3306/design_pattern?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 246812gi
    driver-class-name: com.mysql.cj.jdbc.Driver
####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.redmaple.mapper: DEBUG



