server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/design_pattern?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 246812gi
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.redmaple.mapper: DEBUG
